-- directory structure
-- nvim/
--      after/
--          ftplugin/
--          queries/
--      lua/
--          lsp/
--          luasnip/ 
--              julia/
--              tex/
--      plugin/
--          00options.lua
--          ...
--
--
