function generateLuasnipFile(completions::Dict{String, String}, filename::String; kwargs...)

    directory = "../nvim/lua/luasnip/julia/"
    mkpath(directory)
    outputFile = joinpath(directory, filename)
    println("Generating snippet file at: $(abspath(outputFile))")

    open(outputFile, "w") do f
        write(f, "-- Generated by Julia version $(string(VERSION))\n")
        write(f, "-- Contains $(length(completions)) Unicode and emoji snippets.\n")

        write(f, "  return {\n")
        # END OF CHANGES

        sorted_triggers = sort(collect(keys(completions)))

        for trigger in sorted_triggers
            unicode_chars = completions[trigger]

            lua_trigger = replace(trigger, "\\" => "\\\\", "\"" => "\\\"")
            lua_unicode_output = replace(unicode_chars, "\\" => "\\\\", "\"" => "\\\"")

            desc_parts = []
            for char in unicode_chars
                try
                    info = Base.Unicode.charinfo(char)
                    push!(desc_parts, info.name)
                catch
                    push!(desc_parts, "") # Failsafe
                end
            end

            unicode_name_desc = join(filter(!isempty, desc_parts), " + ")
            final_desc = isempty(unicode_name_desc) ? trigger : "$unicode_chars — $unicode_name_desc"
            lua_desc = replace(trigger, "\\" => "\\\\", "\"" => "\\\"")

            options_list = [
                "trig = \"$(lua_trigger)\"",
                "dscr = \"$(lua_desc)\""
            ]

            for (key, value) in kwargs
                # This part remains the same
                lua_value = ""
                if isa(value, Bool)
                    lua_value = value ? "true" : "false"
                elseif isa(value, Number)
                    lua_value = string(value)
                else
                    lua_value = "\"$(replace(string(value), "\\" => "\\\\", "\"" => "\\\""))\""
                end
                push!(options_list, "$(key)=$(lua_value)")
            end

            lua_options_table = join(options_list, ", ")

            # Indent the snippet one level deeper
            line = """    s({$(lua_options_table)}, { t("$(lua_unicode_output)") }),\n"""
            write(f, line)
        end
        
        # START OF CHANGES
        # 2. Close the table and then the function.
        write(f, "  }\n")
        # END OF CHANGES
    end
    return nothing
end

function createUnicodeCompletionsFile(filename::String="unicodeCompletions.lua", includeEmojis::Bool=true)
    # Start with latex symbols
    completions = copy(REPL.REPLCompletions.latex_symbols)

    if includeEmojis
        # Merge emoji symbols, overwriting any conflicts with the emoji version
        merge!(completions, REPL.REPLCompletions.emoji_symbols)
    end

    println("Generated by Julia version $(string(VERSION))")
    println("Processing $(length(completions)) symbols...")

    # Set LuaSnip options. `wordTrig = false` is important for triggers like `\alpha`.
    generateLuasnipFile(completions, filename; wordTrig=false, snippetType="snippet")
end
