using REPL
using Unicode

function handleLuaEscapes(s::String)
    return replace(s, "\\" => "\\\\", "\"" => "\\\"")
end

function formatLuaValue(v)
    if isa(v, Bool)
        return v ? "true" : "false"
    elseif isa(v, Number)
        return string(v)
    else
        return "\"$(handleLuaEscapes(string(v)))\""
    end
end

function getCharacter(c::Char)
    return Unicode.julia_chartransform(c)
end

function generateLuasnipFile(completions::Dict{String, String}, filename::String; kwargs...)

    directory = "../nvim/lua/luasnip/julia/"
    mkpath(directory)
    outputFile = joinpath(directory, filename)
    println("Generating snippet file at: $(abspath(outputFile))")

    open(outputFile, "w") do f
        write(f, "-- Generated by Julia version $(string(VERSION))\n")
        write(f, "-- Contains $(length(completions)) Unicode and emoji snippets.\n")

        write(f, "  return {\n")

        for trigger in sort(collect(keys(completions)))
            unicodeChars = completions[trigger]

            characters = (getCharacter(c) for c in unicodeChars)
            unicodeNameDesc = join(filter(!isempty, collect(characters)), " + ")
            finalDesc = isempty(unicodeNameDesc) ? trigger : "$trigger — $unicodeNameDesc"


            optionsList = [
                "trig = \"$(handleLuaEscapes(trigger))\"",
                "desc = \"$(handleLuaEscapes(finalDesc))\"" 
            ]

            for (key, value) in kwargs
                push!(optionsList, "$(key)=$(formatLuaValue(value))")
            end

            luaOptionsTable = join(optionsList, ", ")
            line = """    s({$(luaOptionsTable)}, { t("$(handleLuaEscapes(unicodeChars))") }),\n"""
            write(f, line)
        end
        
        write(f, "  }\n")
    end
    return nothing
end

function createUnicodeCompletionsFile(filename::String="unicodeCompletions.lua", includeEmojis::Bool=true)
    # Start with latex symbols
    completions = copy(REPL.REPLCompletions.latex_symbols)

    if includeEmojis
        # Merge emoji symbols, overwriting any conflicts with the emoji version
        merge!(completions, REPL.REPLCompletions.emoji_symbols)
    end

    println("Generated by Julia version $(string(VERSION))")
    println("Processing $(length(completions)) symbols...")

    generateLuasnipFile(completions, filename; wordTrig=false, snippetType="snippet")
end
